SELECT FIRST_NAME, LAST_NAME from employees WHERE SALARY NOT BETWEEN '10000' AND '15000' AND DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 100;
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE from employees WHERE YEAR(HIRE_DATE) = 1987;
SELECT FIRST_NAME FROM employees WHERE FIRST_NAME LIKE '%B%' and FIRST_NAME LIKE '%C%';
SELECT LAST_NAME,JOB_ID,SALARY FROM employees WHERE job_id = 'IT_PROG' or job_id = 'SH_CLERK' and SALARY not in (4500,10000,15000);
SELECT * FROM `employees` WHERE LAST_NAME in ('Blake','Scott','King','Ford');